### ISSUE TITLE
Add a --toggle command

### ISSUE THREAD

**Issue by sbressler** [andornaut/keylight#1]
Would love a toggle command to turn on if off and off if on.

Thanks!

**Comment by 0xdf223** [comment]
Not sure if this repo is actively looked at, but I just put in a PR to add this.

https://github.com/andornaut/keylight/pull/2

**Comment by andornaut** [comment]
@0xdf223 I published [a new version](https://pypi.org/project/keylight/) to PyPI

**Comment by 0xdf223** [comment]
Awesome!
