### ISSUE TITLE
Increase/decrease brightness?

### ISSUE THREAD

**Issue by proffalken** [andornaut/keylight#3]
Hi,

I'm setting up a streamdeck on my Linux laptop and this tool looks like it would be really handy.

Are there any plans to implement the ability to increase/decrease the brightness?

I was thinking something like `keylight -b +20` or `keylight -b -10` to increase/decrease by the required percentage?

**Comment by andornaut** [comment]
Done in [v0.1.3](https://pypi.org/project/keylight/0.1.3/)

**Comment by proffalken** [comment]
Amazing, thank you!
